##
# Ansible playbook for sending the files into build environment
#

---
- hosts: env 
  user: ec2-user
  become: yes
  vars_files:
    - vars/settings.yml

  tasks:
    - include: tasks/websocket.yml



